### ISSUE TITLE
Test that make is installed

### ISSUE THREAD

**Issue by mm689** [kudulab/docker-ansible-dojo#1]
Make is part of the image, should be validated in tests.

**Comment by xmik** [comment]
Make is neither part of the specification of this image, nor it is installed explicitly. Do you @mm689 know which line of [the Dockerfile](https://github.com/kudulab/docker-ansible-dojo/blob/1.2.0/image/Dockerfile) installs it? It is possible that it is installed only to satisfy Ansible runtime dependencies, not as a separate tool for end user to use. If we wanted to test for all the things installed in this image, we should also test for `python python-yaml sudo curl gcc python-pip python-dev libffi-dev libssl-dev` and similar.

What do you think @mm689 ?

**Comment by tomzo** [comment]
@xmik we knew all that. The point is to add `make` as part of the specification because we use it in some project.

**Comment by xmik** [comment]
Ok, I'll do that.

**Comment by xmik** [comment]
Done, released in 1.3.0
